#!/bin/bash

hex_to_rgb () {
    # From https://stackoverflow.com/questions/7253235/convert-hexadecimal-color-to-decimal-rgb-values-in-unix-shell-script
    printf "%d %d %d\n" 0x${1:0:2} 0x${1:2:2} 0x${1:4:2}
}

color_map() {
    for fgbg in 38 48 ; do # Foreground / Background
        for color in {0..255} ; do # Colors
            # Display the color
            printf "\e[${fgbg};5;%sm  %3s  \e[0m" $color $color
            # Display 6 colors per lines
            if [ $((($color + 1) % 6)) == 4 ] ; then
                echo
            fi
        done
        echo
    done
}

_colors () {
    local canary="$HOME/.local/.current_theme"
    local current_theme=dark
    if [[ -e "$canary" ]]; then
        current_theme=$(cat "$canary")
    fi

    declare -A colors
    if [[ "$current_theme" = "dark" ]]; then
        colors[grey]='243'
        colors[green]='40'
        colors[yellow]='220'
        colors[blue]='21'
        colors[lightblue]='45'
        colors[red]='203'
        colors[lightred]='196'
    else
        colors[grey]='249'
        colors[green]='40'
        colors[yellow]='220'
        colors[blue]='21'
        colors[lightblue]='45'
        colors[red]='203'
        colors[lightred]='196'
    fi
    return $colors
}

colorize() {
    local current_theme=dark
    [[ -e "$HOME/.local/.current_theme" ]] && current_theme=$(< "$HOME/.local/.current_theme")

    declare -A colors
    if [[ "$current_theme" = "dark" ]]; then
        colors=([grey]=243 [green]=40 [yellow]=220 [blue]=27 [lightblue]=45 [red]=203 [lightred]=196)
    else
        colors=([grey]=249 [green]=40 [yellow]=94 [blue]=21 [lightblue]=45 [red]=203 [lightred]=196)
    fi

    if [[ "$1" = "help" ]]; then
        echo "Usage: colorize [--prefix TEXT [--prefix-color COLOR]] <pattern1> <color1> [pattern2 color2...] <input>"
        echo "Single-process colorizer (sed -u)."
        echo "Possible colors:"
        for i in "${!colors[@]}"; do
            echo -e "    \e[1;38;5;${colors[$i]}m$i\e[0m"
        done
        echo "Special: 'remove' filters out lines, 'all' matches everything."
        return
    fi

    local esc=$'\033'
    local prefix_args=() remove_args=() color_args=()

    if [[ "$1" = "--prefix" ]]; then
        local prefix="$2"; shift 2
        if [[ "$1" = "--prefix-color" ]]; then
            local pcode="${colors[$2]:-$2}"
            shift 2
            prefix_args=(-e "s|^|${esc}[1;38;5;${pcode}m${prefix}${esc}[0m|")
        else
            prefix_args=(-e "s|^|${prefix}|")
        fi
    fi

    while [[ $# -ge 2 ]]; do
        local pat="$1" col="$2"
        shift 2
        [[ "$pat" = "all" ]] && pat=".*"
        pat="${pat//\//\\/}"
        if [[ "$col" = "remove" ]]; then
            remove_args+=(-e "/${pat}/d")
        else
            local code="${colors[$col]:-$col}"
            color_args+=(-e "s/${pat}/${esc}[1;38;5;${code}m&${esc}[0m/g")
        fi
    done

    sed -E -u "${remove_args[@]}" "${prefix_args[@]}" "${color_args[@]}"
}

alias _color_debug='colorize DEBUG grey INFO green WARNING yellow ERROR red CRITICAL lightred'
alias _color_info='colorize DEBUG remove INFO green WARNING yellow ERROR red CRITICAL lightred'
alias _color_warning='colorize DEBUG remove INFO remove WARNING yellow ERROR red CRITICAL lightred'
