#!/usr/bin/env python
from __future__ import print_function

import sys
import subprocess

USAGE = '''
    Usage : gitstore [-u] [-n] target

    cherry-pick last commit on current branch on there [target] branch,
    push it to my fork (if [-u] is set), then switch back to the initial
    branch.

    -u : Push target branch to remote configured with :
        git config --add upload.fork <mine>

    -n : Force branch creation from master

'''


def run_cmd(cmd, handle_error=True):
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    res, errs = p.communicate()
    if not handle_error:
        return res, errs
    if errs:
        print(errs, file=sys.stderr)
        sys.exit()
    return res, errs

# Get branch list
branches, errs = run_cmd(['git', 'branch'], False)

if errs:
    print(errs, file=sys.stderr)
    print(USAGE)
    sys.exit()

cur_branch = [x.lstrip('* ')
    for x in branches.split('\n') if x.startswith('* ')][0]
branches = [x.lstrip('* ') for x in branches.split('\n') if x]

create_branch = True
try:
    sys.argv.remove('-n')
except ValueError:
    create_branch = False

target_remote = ''
try:
    sys.argv.remove('-u')
    target_remote = 'tmp'
except ValueError:
    pass
if target_remote:
    target_remote = run_cmd(['git', 'config', '--get', 'upload.fork'], False)
    if not target_remote:
        print(USAGE)
        sys.exit()
    target_remote = target_remote[0][:-1]

if len(sys.argv) != 2:
    print(USAGE)
    sys.exit()

if not create_branch:
    target = [x for x in branches if x.startswith(sys.argv[1])]
    if len(target) == 1:
        target = target[0]
    elif len(target) > 1:
        print('"%s" is not a unique branch prefix' % sys.argv[1])
        [print('    ' + x) for x in target]
        print('')
        sys.exit()
    elif not target:
        print('No branch found matching %s' % sys.argv[1])
        print('')
        run_cmd(['git', 'branches'])
        sys.exit()
else:
    target = sys.argv[1]

print('Stashing, just in case')
run_cmd(['git', 'stash', 'save', 'tmp_for_gitstore'], False)

if target == cur_branch:
    print('Already on %s, only pushing' % target)
elif not create_branch:
    print('Switching branch to %s' % target)
    run_cmd(['git', 'checkout', target], False)
else:
    print('Creating new branch %s' % target)
    run_cmd(['git', 'checkout', 'master'], False)
    run_cmd(['git', 'checkout', '-b', target], False)

if target != cur_branch:
    print('Cherry picking')
    run_cmd(['git', 'cherry-pick', cur_branch])

if target_remote:
    print(target_remote)
    print('Pushing to %s' % target_remote)
    subprocess.Popen(['git', 'push', target_remote]).communicate()
    run_cmd(['git', 'branch', '--set-upstream-to=%s/%s' % (target_remote,
        target), target], False)

if target != cur_branch:
    print('Switching back to %s' % cur_branch)
    run_cmd(['git', 'checkout', cur_branch], False)

print('Restoring stash')
subprocess.Popen(
    ['git', 'stash', 'pop']).communicate()
