#!/usr/bin/env python
import subprocess
import sys

p = subprocess.Popen(['git', 'branch', '-a', '--list', '--no-color'],
                     stdout=subprocess.PIPE)
res, errs = p.communicate()
if errs:
    sys.exit()
branches = [x.strip('*').strip() for x in res.strip().split('\n')]
remotes = set([x.split(' ')[0].split('/')[-1]
              for x in branches if x.startswith('remotes')])
locales = set([x for x in branches if not x.startswith('remotes')
              and x not in remotes and not x.startswith('(HEAD ')])
if not locales:
    sys.exit()
for branch in locales:
    print(branch)
