#!/usr/bin/env python
import os
import sys
import subprocess

base_dir = os.environ.get('WORKON_HOME')
if not base_dir:
    print('$WORKON_HOME not set, exiting')
    sys.exit()

for env_name in os.listdir(base_dir):
    full_path = os.path.join(base_dir, env_name)
    if not os.path.isdir(full_path):
        continue
    project_file = os.path.join(full_path, '.project')
    if os.path.exists(project_file):
        with open(project_file, 'r') as f:
            full_path = f.read().strip()

    print('\nProject path : %s' % full_path)

    for cur_dir in os.listdir(full_path):
        if not os.path.exists(os.path.join(full_path, cur_dir, '.git')):
            continue
        target = os.path.join(full_path, cur_dir)
        p = subprocess.Popen(['git', '-C', target, 'fetch', '-p', 'origin'],
                stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        p.communicate()
        p = subprocess.Popen(['git', '-C', target, 'fetch', '-p', 'mine'],
                stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        p.communicate()
        p = subprocess.Popen(['git', '-C', target, 'branch', '-vv'],
                stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        res, errs = p.communicate()
        if errs:
            print('    %s :' % cur_dir)
            print('        ERROR : %s' % errs)
            continue
        branches = [x.strip('*').strip() for x in res.strip().split('\n')]
        for branch in branches:
            data = [x for x in branch.split(' ') if x]
            if (len(data) > 3 and data[3] == 'gone]' and data[2][0] == '[' and
                    data[2][-1] == ':'):
                print(' '.join(data))
print('\n')
