#!/usr/bin/env python
import sys
import os
import json

from subprocess import Popen, PIPE

try:
    with open(os.path.join(os.getenv('HOME'), '.review_groups'), 'r') as f:
        groups = json.loads(f.read())
except:
    print "Could not find .review_groups in your home directory"
    print ''
    sys.exit()

if len(sys.argv) != 3:
    print "Usage : gitup 'message' user"
    print ''
    print 'Message may be empty ("")'
    print ''
    print '\n\t'.join(['Possible groups :\n\t'] + groups.keys())
    print ''
    sys.exit()
message = sys.argv[1]
group = sys.argv[2]

mrg_bas = Popen(['git', 'merge-base', 'HEAD', 'origin/master'],
    stdout=PIPE)
mrg_bas, errs = mrg_bas.communicate()
if errs:
    print errs
    sys.exit()

cmd = ['git', 'cl', 'upload', mrg_bas[:-1], '-r', groups.get(group, group)]
if message:
    cmd += ['-m', message]
else:
    cmd += ['-u']
process = Popen(cmd)
process.communicate()
