#!/usr/bin/env python
import sys
import os

from subprocess import Popen, PIPE

process = Popen(['hg', 'review', '--id'], stdout=PIPE)
review_id, errors = process.communicate()
review_id = review_id.split('\n')[0]

if len(sys.argv) == 2:
    review_id = sys.argv[1]
    process = Popen(['hg', 'root'], stdout=PIPE)
    root_path, errors = process.communicate()
    root_path = root_path.split('\n')[0]
    Popen('rm ' + os.path.join(root_path, '.hg', 'review_id'),
        shell=True).communicate()
elif not review_id:
    print 'Usage (if no current review) : hgfe review_id'
    sys.exit()

process = Popen(['hg', 'review', '--fetch', '--issue', review_id],
    stdout=PIPE, stdin=PIPE)

# \n to accept the email
output, errors = process.communicate('\n')
if errors:
    print errors
    sys.exit()
print output
