#!/bin/sh
rm -rf /tmp/test_vim
mkdir -p /tmp/test_vim
cd /tmp/test_vim/ || exit
export XDG_CONFIG_HOME=/tmp/test_vim/.config
export XDG_DATA_HOME=/tmp/test_vim/.data
export XDG_CACHE_HOME=/tmp/test_vim/.cache
mkdir -p /tmp/test_vim/.config
ln -s ~/Projets/Nvimrc/dotfiles/nvim /tmp/test_vim/.config/nvim
~/Projets/Neovim/build/bin/nvim
