#!/usr/bin/bash
# Terminate already running bar instances
pkill -x waybar

# Wait until the processes have been shut down
while pgrep -x waybar >/dev/null; do sleep 1; done

# Launch main
waybar -c ~/dotfiles/waybar/config -s ~/dotfiles/waybar/style.css
