#!/bin/bash
if [[ "${1::3}" = "Dev" ]]; then
    i3-msg workspace "$1"
elif [[ "${1:-}" != "" ]]; then
    i3-msg workspace "Dev_$1"
    i3-msg gaps outer current set 100
    i3-msg gaps inner current set 20
    i3-msg exec 'alacritty --working-directory "$HOME"'
fi
