#!/bin/bash
existing=`tmux list-windows | grep $1-shell | wc -l`
if [ $existing = '1' ]; then
    echo "Found window $1-shell, switching..."
    tmux find-window -N $1-shell
    exit
fi
current_number=`tmux list-windows | wc -l`
new_shell=$(($current_number + 1))
new_code=$(($current_number + 2))
tmux new-window -t $new_shell -n $1-shell
tmux new-window -t $new_code -n $1-code
tmux select-window -t $new_shell
sleep 2
tmux send-keys -t $new_shell "workon $1;clear" Enter
tmux send-keys -t $new_code "workon $1;clear;$EDITOR" Enter
