#!/bin/bash
existing=$(tmux list-windows | grep -c "$1 Shell")
if [ "$existing" = '1' ]; then
    echo "Found window $1 Shell, switching..."
    tmux find-window -N "$1 Shell"
    exit
fi
current_number=$(tmux list-windows | wc -l)
new_shell=$(("$current_number" + 1))
new_code=$(("$current_number" + 2))
tmux new-window -t $new_shell -n "$1 Code"
tmux new-window -t $new_code -n "$1 Shell"
tmux select-window -t $new_shell
sleep 2
tmux send-keys -t $new_shell "workon $2;clear" C-m
tmux send-keys -t $new_code "workon $2;clear;$EDITOR" C-m
