#!/usr/bin/bash
mkdir -p "$HOME/Pictures"
mkdir -p "$HOME/Pictures/Wallpapers"
cd "$HOME/Pictures/Wallpapers"

dl_wallpaper() {
    # Thanks https://github.com/bijanebrahimi/waffle/
    export DISPLAY=:0
    UA="Mozilla/5.0 (iPad; U; CPU OS 3_2_1 like Mac OS X; en-us) AppleWebKit/531.21.10 (KHTML, like Gecko) Mobile/7B405"
    CAT=$(echo -e "travel\nfantasy\nspace\nnature" | shuf -n1)
    URL=http://wallpaperswide.com/download$( \
        curl -sc /tmp/wallpaperswide.cookie -s \
            http://wallpaperswide.com/${CAT}-desktop-wallpapers/page/` \
                shuf -i 1-100 -n 1` \
            | grep -o "\/[^\"]*-wallpapers.html" | grep -v "desktop" | uniq | \
            shuf -n1 | sed 's/wallpapers.html/wallpaper-3840x2160.jpg/g')

    FILENAME=/tmp/random_wallpaper/"$CAT"-$(basename "${URL}")
    curl -s --cookie /tmp/wallpaperswide.cookie -A "${UA}" "${URL}" -o "${FILENAME}"
}

export -f dl_wallpaper

_fetch() {
    WALLPAPER_FOLDER="$HOME/Pictures/Wallpapers"
    while true; do
        mkdir -p /tmp/random_wallpaper
        rm -f /tmp/random_wallpaper/*
        dl_wallpaper
        filename=$(ls -1 /tmp/random_wallpaper/ | head -n1)
        filesize=$(wc -c /tmp/random_wallpaper/$filename | awk '{print $1}')
        if [[ $filesize != 0 ]]; then
            cp /tmp/random_wallpaper/$filename "$WALLPAPER_FOLDER"
            cp /tmp/random_wallpaper/$filename "$WALLPAPER_FOLDER/last_wallpaper"
            break
        fi
    done
}

export -f _fetch

_display() {
    existing_pid=$(pgrep swaybg)
    (nohup swaybg -i "$HOME/Pictures/Wallpapers/$1" >/dev/null 2>&1 &)
    sleep 0.01
    if [[ "$existing_pid" ]]; then
        for pid in $existing_pid; do
            kill "$pid"
        done
    fi
}

export -f _display

wallpaper=$(fzf --bind='ctrl-p:execute: _display {1}' \
    --bind='ctrl-n:execute: _fetch'\
    --bind='ctrl-r:reload(ls)')

if [[ "$wallpaper" ]]; then
    _display "$wallpaper"
fi
