#!/usr/bin/env bash

WALLPAPER_FOLDER="$HOME/Pictures/Wallpapers"

declare -A DOWNLOADS

DOWNLOADS[wall0.jpg]=http://hdqwalls.com/wallpapers/galaxy-space-stars-universe-nebula-4k-qw.jpg
DOWNLOADS[wall1.jpg]=https://wallpapersite.com/images/wallpapers/stars-3840x2160-4k-6347.jpg
DOWNLOADS[wall2.jpg]=http://hdqwalls.com/download/1/space-dark-dust-galaxy-nebula-tg-3840x2160.jpg
DOWNLOADS[wall3.jpg]=http://hdqwalls.com/download/1/space-digital-art-galaxy-54-3840x2160.jpg

if [[ ! -e "$HOME"/Pictures/Wallpapers ]]; then
    mkdir -p "$HOME"/Pictures
    mkdir -p "$WALLPAPER_FOLDER"
fi

for name in "${!DOWNLOADS[@]}"; do
    if [[ ! -e "$WALLPAPER_FOLDER/$name" ]]; then
        curl ${DOWNLOADS[$name]} > "$WALLPAPER_FOLDER/$name"
    fi
done

sleep 2

feh --bg-fill --randomize ~/Pictures/Wallpapers/*
