#!/usr/bin/env bash

WALLPAPER_FOLDER="$HOME/Pictures/Wallpapers"
mkdir -p $WALLPAPER_FOLDER

declare -A DOWNLOADS

# DOWNLOADS[wall0.jpg]=https://hdqwalls.com/wallpapers/galaxy-space-stars-universe-nebula-4k-qw.jpg

if [[ ! -e "$HOME"/Pictures/Wallpapers ]]; then
    mkdir -p "$HOME"/Pictures
    mkdir -p "$WALLPAPER_FOLDER"
fi

for name in "${!DOWNLOADS[@]}"; do
    if [[ ! -e "$WALLPAPER_FOLDER/$name" ]]; then
        curl -L ${DOWNLOADS[$name]} > "$WALLPAPER_FOLDER/$name"
    fi
    if [[ ! -s "$WALLPAPER_FOLDER/$name" ]]; then
        rm "$WALLPAPER_FOLDER/$name"
    fi
done

dl_wallpaper() {
    # Thanks https://github.com/bijanebrahimi/waffle/
    export DISPLAY=:0
    UA="Mozilla/5.0 (iPad; U; CPU OS 3_2_1 like Mac OS X; en-us) AppleWebKit/531.21.10 (KHTML, like Gecko) Mobile/7B405"
    CAT=$(echo -e "travel\nfantasy\nspace\nnature" | shuf -n1)
    echo -e "category\t${CAT}"
    URL=http://wallpaperswide.com/download$( \
        curl -c /tmp/wallpaperswide.cookie -s \
            http://wallpaperswide.com/${CAT}-desktop-wallpapers/page/` \
                shuf -i 1-100 -n 1` \
            | grep -o "\/[^\"]*-wallpapers.html" | grep -v "desktop" | uniq | \
            shuf -n1 | sed 's/wallpapers.html/wallpaper-3840x2160.jpg/g')

    echo -e "url\t$URL"
    FILENAME=/tmp/random_wallpaper/"$CAT"-$(basename "${URL}")
    curl --cookie /tmp/wallpaperswide.cookie -A "${UA}" "${URL}" -o "${FILENAME}"
}

while true; do
    mkdir -p /tmp/random_wallpaper
    rm -f /tmp/random_wallpaper/*
    dl_wallpaper
    filename=$(ls -1 /tmp/random_wallpaper/ | head -n1)
    filesize=$(wc -c /tmp/random_wallpaper/$filename | awk '{print $1}')
    if [[ $filesize != 0 ]]; then
        rm $WALLPAPER_FOLDER/*
        cp /tmp/random_wallpaper/$filename "$WALLPAPER_FOLDER"
        break
    fi
done

feh --bg-fill --randomize ~/Pictures/Wallpapers/*
